-- Executor slice 1: injected signals, position book, decision audit.

CREATE TABLE executor_signal (
    signal_id       TEXT PRIMARY KEY,
    source          TEXT NOT NULL,
    agent_version   TEXT,
    symbol          TEXT NOT NULL,
    direction       TEXT NOT NULL,
    confidence      NUMERIC(4,3),
    mechanism       TEXT,
    kill_criteria   JSONB NOT NULL DEFAULT '[]',
    horizon         TEXT,
    reference_price NUMERIC(18,6),
    status          TEXT NOT NULL DEFAULT 'PENDING',
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    processed_at    TIMESTAMPTZ
);
CREATE INDEX idx_executor_signal_status ON executor_signal (status, created_at);

CREATE TABLE executor_position (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    connection       TEXT NOT NULL,
    symbol           TEXT NOT NULL,
    side             TEXT NOT NULL,
    qty              NUMERIC(18,6) NOT NULL,
    entry_price      NUMERIC(18,6) NOT NULL,
    initial_stop     NUMERIC(18,6) NOT NULL,
    active_stop      NUMERIC(18,6) NOT NULL,
    tranche          INTEGER NOT NULL DEFAULT 1,
    r_value          NUMERIC(18,6),
    kill_criteria    JSONB NOT NULL DEFAULT '[]',
    source_signal_id TEXT,
    source_agent     TEXT,
    entry_date       TIMESTAMPTZ NOT NULL DEFAULT now(),
    mfe              NUMERIC(18,6),
    status           TEXT NOT NULL DEFAULT 'OPEN',
    broker_order_id  TEXT
);
CREATE INDEX idx_executor_position_status ON executor_position (status, symbol);

CREATE TABLE executor_decision (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    signal_id        TEXT,
    symbol           TEXT NOT NULL,
    accepted         BOOLEAN NOT NULL,
    reject_reason    TEXT,
    veto_trace       JSONB NOT NULL DEFAULT '[]',
    rationale        TEXT,
    broker_order_id  TEXT,
    run_id           TEXT,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_executor_decision_created ON executor_decision (created_at DESC);
