-- Slice 2: exit lifecycle + rich decision logging.

ALTER TABLE executor_position ADD COLUMN highest_price     NUMERIC(18,6);
ALTER TABLE executor_position ADD COLUMN mfe_r             NUMERIC(18,6);
ALTER TABLE executor_position ADD COLUMN soft_confirm_count INTEGER NOT NULL DEFAULT 0;
ALTER TABLE executor_position ADD COLUMN exit_price        NUMERIC(18,6);
ALTER TABLE executor_position ADD COLUMN realized_r        NUMERIC(18,6);
ALTER TABLE executor_position ADD COLUMN exit_reason       TEXT;
ALTER TABLE executor_position ADD COLUMN closed_at         TIMESTAMPTZ;
ALTER TABLE executor_position ADD COLUMN stop_order_id     TEXT;

CREATE TABLE decision_log (
    log_id                 UUID PRIMARY KEY,
    ts_decision            TIMESTAMPTZ NOT NULL DEFAULT now(),
    run_id                 TEXT,
    rule_version           TEXT NOT NULL,
    trigger_type           TEXT NOT NULL,
    signal_id              TEXT,
    source_agent           TEXT,
    source_agent_version   TEXT,
    symbol                 TEXT,
    inputs_snapshot        JSONB NOT NULL DEFAULT '{}',
    veto_results           JSONB NOT NULL DEFAULT '[]',
    action                 TEXT NOT NULL,
    reason_code            TEXT,
    order_json             JSONB,
    reasoning              TEXT,
    confidence_in_decision NUMERIC(4,3),
    latency                JSONB,
    created_at             TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_decision_log_created ON decision_log (created_at DESC);
CREATE INDEX idx_decision_log_symbol  ON decision_log (symbol, created_at DESC);

CREATE TABLE rule_versions (
    rule_version TEXT PRIMARY KEY,
    valid_from   DATE NOT NULL,
    changes      TEXT,
    prompt_hash  TEXT,
    params       JSONB NOT NULL DEFAULT '{}'
);

CREATE TABLE cooldown (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    symbol              TEXT NOT NULL,
    reason              TEXT,
    expires_at          TIMESTAMPTZ NOT NULL,
    exception_condition TEXT,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_cooldown_symbol ON cooldown (symbol, expires_at);
