-- V26: spin-off lifecycle persistence. Tracks each spin-co registration from its
-- Form 10-12B filing through the WHEN_ISSUED / DISTRIBUTED / SETTLED window (or
-- ABANDONED), so the hunter is no longer single-shot/stateless. Status is plain
-- TEXT (validated by the Java SpinStatus enum, like executor_signal.status, not a
-- DB enum); no hard FK to prey (soft promoted_prey_id); idempotency via an
-- expression unique index on COALESCE(cik, lower(company_name)) -- same technique
-- as V21's uq_prey_natural_day. Per-stage enrichment lands in the JSONB snapshots
-- (populated by later slices).

CREATE TABLE spin_candidate (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cik                   TEXT,
    symbol                TEXT,
    company_name          TEXT NOT NULL,
    form_type             TEXT,
    filing_date           DATE,
    filing_url            TEXT,
    distribution_ratio    TEXT,
    record_date           DATE,
    distribution_date     DATE,
    term_sheet_available  BOOLEAN NOT NULL DEFAULT false,
    -- Raw information-statement / term-sheet prose. Deliberately kept (a few KB per rare
    -- spin-off) against the blueprint's lean-table preference: the spin thesis (parent identity,
    -- relative size, mandate-driven forced-selling language, business trend) lives ONLY in this
    -- prose, and the LLM prompt asks the hunter to read it when term_sheet_available is true.
    -- Persisting it keeps term_sheet_available truthful and the payload's termSheet coherent
    -- instead of sending available=true with a null body.
    term_sheet_text       TEXT,
    -- Best-effort parent ticker extracted from an exchange-qualified parenthetical in the term
    -- sheet (e.g. "Parent Corp (NYSE: XYZ)"); null when only a name (no ticker) appears -- no
    -- unreliable name->ticker heuristic. Drives the DISTRIBUTED-stage sizeRatio when resolvable.
    parent_symbol         TEXT,
    status                TEXT NOT NULL DEFAULT 'REGISTERED',
    registered_snapshot   JSONB,
    distributed_snapshot  JSONB,
    settled_snapshot      JSONB,
    promoted_at           TIMESTAMPTZ,
    promoted_prey_id      TEXT,
    discovered_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_checked_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    distributed_at        TIMESTAMPTZ,
    settled_at            TIMESTAMPTZ,
    abandoned_at          TIMESTAMPTZ
);

-- Natural-key idempotency: one row per spin-co, keyed on its CIK when known,
-- degrading to the lowercased company name before a CIK is available. The
-- ingestion upsert (ON CONFLICT DO NOTHING) targets this expression and the
-- SpinoffScreener dedup key mirrors it exactly.
CREATE UNIQUE INDEX uq_spin_candidate_natural
  ON spin_candidate (COALESCE(cik, lower(company_name)));

-- Reconciliation scan: non-terminal rows, oldest-checked first. The reconciler's
-- ORDER BY last_checked_at ASC drives the scan; a status-leading index cannot serve
-- that ordering (status is filtered with a multi-valued NOT IN), so the index is on
-- the sort key directly. The terminal-status filter is a cheap residual on the
-- already-ordered stream.
CREATE INDEX idx_spin_candidate_last_checked ON spin_candidate (last_checked_at);

-- Promotion scan: DISTRIBUTED, not-yet-promoted rows, oldest-distributed first.
-- Partial on promoted_at IS NULL (so promoted_at needn't be an index column), with
-- (status, distributed_at) carrying both the status filter and the ORDER BY.
CREATE INDEX idx_spin_candidate_promotable ON spin_candidate (status, distributed_at)
  WHERE promoted_at IS NULL;
