-- V27: index-reconstitution lifecycle persistence. Tracks each S&P/Russell
-- constituent change from its public announcement (window still open) through the
-- EFFECTIVE day into the POST run-up/reversal observation window (or ABANDONED), so
-- strigoi-index is no longer single-shot/stateless and can anchor on the announcement
-- date rather than the already-closed effective date. Status is plain TEXT (validated
-- by the Java IndexEventStatus enum, like spin_candidate.status / executor_signal.status,
-- not a DB enum); no hard FK to prey (soft promoted_prey_id); idempotency via an
-- expression unique index on (index_name, upper(symbol), action, effective_date) -- one
-- row per announced change (subjects are existing ticker-bearing companies, so no
-- CIK/name degradation like spin). Per-stage enrichment lands in the JSONB snapshots
-- (populated by later slices). Only TWO snapshots (announced/post) -- EFFECTIVE is a
-- transient calendar tick, not an observation stage.

CREATE TABLE index_event (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    symbol              TEXT NOT NULL,
    company_name        TEXT,
    index_name          TEXT NOT NULL,
    action              TEXT NOT NULL,
    source              TEXT NOT NULL,
    announcement_date   DATE NOT NULL,
    effective_date      DATE NOT NULL,
    status              TEXT NOT NULL DEFAULT 'ANNOUNCED',
    announced_snapshot  JSONB,
    post_snapshot       JSONB,
    promoted_at         TIMESTAMPTZ,
    promoted_prey_id    TEXT,
    discovered_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_checked_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    effective_at        TIMESTAMPTZ,
    closed_at           TIMESTAMPTZ,
    abandoned_at        TIMESTAMPTZ
);

-- Natural-key idempotency: one row per announced constituent change, keyed on the
-- index, the upper-cased ticker, the direction, and the effective date. The ingestion
-- upsert (ON CONFLICT DO NOTHING) targets this exact expression, so re-running the hunt
-- never duplicates a change nor resets its lifecycle.
CREATE UNIQUE INDEX uq_index_event_natural
  ON index_event (index_name, upper(symbol), action, effective_date);

-- Reconciliation scan: non-terminal rows, oldest-checked first. The reconciler's
-- ORDER BY last_checked_at ASC drives the scan (status is filtered with a multi-valued
-- NOT IN, which a status-leading index cannot serve), so the index is on the sort key
-- directly; the terminal-status filter is a cheap residual on the already-ordered stream.
CREATE INDEX idx_index_event_last_checked ON index_event (last_checked_at);

-- Partial index for the not-yet-promoted working set (promoted_at IS NULL), leading on
-- (status, effective_date). It serves the status-filtered scans (findActiveUnpromoted's
-- status IN (...) predicate, findPromotableBySymbol's status = 'ANNOUNCED'); it does NOT
-- cover findActiveUnpromoted's ORDER BY discovered_at (a residual sort), nor is it what
-- resolves findPromotableBySymbol's upper(symbol) point-lookup (that scans the small
-- filtered set). At this table's cardinality (dozens of events/year) that is fine — no
-- discovered_at / upper(symbol) index is warranted; this partial index just keeps the
-- promoted rows out of the way.
CREATE INDEX idx_index_event_promotable ON index_event (status, effective_date)
  WHERE promoted_at IS NULL;
