-- Persisted equity time series per depot connection. Replaces the synthesised curve in
-- DepotChartService, which valued TODAY's holdings at historical closes and therefore could
-- never show a position that had been sold -- see docs/superpowers/specs/2026-08-27-depot-equity-curve-a0-design.md.
--
-- equity/cash are stored exactly as the broker reports them, in the account's own currency.
-- Nothing here is ever summed across currencies.
--
-- granularity is what answers "which row is the day's close": without it a query would have to
-- guess "last row of the day" and would silently serve a pre-close intraday point on any day the
-- daily job failed.
--
-- external_flow and source are written with their defaults only in this slice. They exist now so
-- the reconstruction slice and the cash-flow slice need no further migration.
CREATE TABLE depot_equity_snapshot (
    id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    connection       text          NOT NULL,
    as_of            timestamptz   NOT NULL,
    granularity      text          NOT NULL,
    equity           numeric(18,2) NOT NULL,
    cash             numeric(18,2) NOT NULL,
    positions_value  numeric(18,2) NOT NULL,
    currency         text          NOT NULL,
    external_flow    numeric(18,2) NOT NULL DEFAULT 0,
    source           text          NOT NULL DEFAULT 'MEASURED',
    CONSTRAINT depot_equity_snapshot_source_ck
        CHECK (source IN ('MEASURED','RECONSTRUCTED')),
    CONSTRAINT depot_equity_snapshot_granularity_ck
        CHECK (granularity IN ('DAILY','INTRADAY')),
    CONSTRAINT depot_equity_snapshot_uk UNIQUE (connection, granularity, as_of)
);
